### ISSUE TITLE
Example code in readme doesn't work.

### ISSUE THREAD

**Issue by TrevTheDev** [incetarik/fp-ts-stream#1]
The example code in the readme doesn't work - `fp-ts` doesn't have a `pipe` function `toArray` is probably missing from the import.  Also has type errors.  I tried ramda's pipe function, but the code didn't work.

**Comment by incetarik** [comment]
How did not I realize that until now? Thank you for your feedback. Pretty busy these days, missed it. Will fix it in the following hours. 

And for fp-ts, it does have a pipe function, could you please check it again? I have probably imported it from somewhere else rather than the one that I should import from.

**Comment by incetarik** [comment]
@TrevTheDev The readme is updated, please check it out. Thank you for your feedback.

**Comment by TrevTheDev** [comment]
@incetarik  - I've been exploring your project - and it is awesome - I love it and can see so many use-cases for this.  Thanks for sharing and well done!
